name: Patch Mikrotik RouterOS (Local)

on:
  workflow_dispatch:  # تشغيل يدوي من Actions

permissions:
  contents: write

jobs:
  patch-local-npk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pefile p7zip-full squashfs-tools

    - name: Patch local NPK file
      env:
        CUSTOM_LICENSE_PRIVATE_KEY: ${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}
        CUSTOM_LICENSE_PUBLIC_KEY: ${{ secrets.CUSTOM_LICENSE_PUBLIC_KEY }}
        CUSTOM_NPK_SIGN_PRIVATE_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PRIVATE_KEY }}
        CUSTOM_NPK_SIGN_PUBLIC_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PUBLIC_KEY }}
        MIKRO_LICENSE_PUBLIC_KEY: ${{ secrets.MIKRO_LICENSE_PUBLIC_KEY }}
        MIKRO_NPK_SIGN_PUBLIC_KEY: ${{ secrets.MIKRO_NPK_SIGN_PUBLIC_KEY }}
      run: |
        python3 patch.py npk routeros-mmips-6.47.9.npk -o routeros-mmips-6.47.9-patched.npk

    - name: Upload patched file
      uses: actions/upload-artifact@v4
      with:
        name: patched-npk
        path: routeros-mmips-6.47.9-patched.npk
